[package]
name = "ext4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
failure = "0.1.8"
positioned-io = "0.2.2"
